server:
  port: 3344
spring:
  application:
    name: cloud-config-center   #注册进Eureka的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuxinha/springcloud-config.git  #GitHub上面仓库的clone地址
          #搜索目录
          search-paths:
            - springcloud-config
      label: master

#服务注册到Eureka
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka

#rabbitMQ相关配置
rabbitmq:
  host: localhsot
  port: 5672
  username: guest
  password: guest

#暴露监控端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"